require './config/ember'
require './config/zooniverse'
require './config/routes'

require './lib/helpers'
require './routes/all'
require './controllers/all'
require './views/all'
require './templates/all'
require './components/all'
